version: '3.5'
services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
    ports:
      - 3306:3306
      - 33060:33060
  stock:
    image: lucasvilela/stock-manager
    ports:
      - 8080:8080
